### ISSUE TITLE
ItemTemplate Syntax not valid (Dutch)

### ISSUE THREAD

**Issue by WouterKessener** [scottdurow/power-drag-drop#13]
Hi Scott, really really looking forward using the DD component.  Ran into a little problem.  Please see screenshot.

![image](https://user-images.githubusercontent.com/15956643/207037934-e91ae52f-0f9a-4a8e-b955-8b2db3482c12.png)

Any hints, saw it working in your video. Maybe a language issue?

**Comment by WouterKessener** [comment]
This seems to bee the solution. 

![image](https://user-images.githubusercontent.com/15956643/207056760-05748ab4-5b98-481b-98ca-d8456fcc7883.png)

**Comment by scottdurow** [comment]
Hi @WouterKessener - Yes, when you paste into the ItemTemplate - you'll need to use the format you show above - or paste directly into the Item Template Field on the properties panel on the right, where it'll format for you automatically.
