### ISSUE TITLE
 'An Unknown error occurred' Error when importing the solution

### ISSUE THREAD

**Issue by gokulnathgit** [scottdurow/power-drag-drop#24]
Hi @scottdurow ,

I have downloaded the unmanaged and managed solution from recent release.
https://github.com/scottdurow/power-drag-drop/releases/tag/v1.0.26.

While importing it's throwing an error. 'An Unknown error occurred'. Please assist on this. 

Thank-you.

**Comment by gokulnathgit** [comment]
Please ignore..

**Comment by scottdurow** [comment]
What does it say in the history tab under solutions?
![image](https://user-images.githubusercontent.com/2871121/214700987-6c676938-836c-4ff8-a0c0-df51264a3446.png)

Open the import solution failure row and see if there are any more details or if you can download the log file.
![image](https://user-images.githubusercontent.com/2871121/214701159-36f40300-2609-4124-af24-b8c21e52f1ff.png)

Thanks!

**Comment by gokulnathgit** [comment]
Hi @scottdurow , Thank you for your input on this. I analyzed the error history , I didn't had a enough privilege to deploy this solution. Now I can deploy the solution without any error.
Thank-you for your assistance.

**Comment by scottdurow** [comment]
Awesome - thank you for the update 🚀
