### ISSUE TITLE
Drop zone not scrolling on iPad

### ISSUE THREAD

**Issue by Maverick90274** [scottdurow/power-drag-drop#30]
Hello Scott,
Your Power Drag and Drop is awesome! thank you so much for sharing it!
The app i made works great on the computer because i can use the mouse to scroll but on the iPad i can't scroll the dropzones. every time i try the app moves the content of the dropzones.
I already tried to set the direction to vertical, but it does not solve it.
Is there a way to make it work on the iPad too?

Thank you!

![MSiPad](https://user-images.githubusercontent.com/126905429/222791933-7e2fa135-9465-4732-bc1f-d657eeed6b9e.png)

**Comment by scottdurow** [comment]
Hi @Maverick90274 - app is looking great - nice job.

Could you try setting the `DelaySelect` property to `TouchOnly` on the drop zones. This will ensure that when you touch the drop zone it will give you time to start scrolling before trying to select an item.

Check that you have the latest version as well (1.0.27)

Thanks!
Scott

**Comment by Maverick90274** [comment]
That’s awesome! Thank you!
It’s work and it is so cool on the iPad! Our team loves the app.
Thank you again Scott!

**Comment by scottdurow** [comment]
Fantastic news! Thank you for the update 🚀
