### ISSUE TITLE
Question: Is it possible to prevent an item from one slave zone to another slave zone?

### ISSUE THREAD

**Issue by Maverick90274** [scottdurow/power-drag-drop#39]
Hello Scott!
I hope you are doing well!
I have one master zone and multiple slaves zones.
Once the item has been dragged and drop from the master to a slave, i would like to prevent the user to move the item to another slave.
I would like the user to delete the item from the slave zone, so i will go back to the master and then have the user drag and drop it to another slave zone.
Is this possible?

Thank you!

**Comment by scottdurow** [comment]
Hi @Maverick90274 - you would need to perform some OnDrop validation logic and display a message to the user indicating that the drop is not valid - then update the items accordingly. A drop zone can be configured to have a maximum number of items, but it is not yet possible to configure individual items to have valid target zones. I'll add it to the backlog!

**Comment by Maverick90274** [comment]
Thank you for the quick feedback Scott!
