### ISSUE TITLE
Privilege: prvCreateCustomControl

### ISSUE THREAD

**Issue by Fernando-Rivero** [scottdurow/power-drag-drop#41]
Hello, a pleasure to greet you. When I want to import the solution power drag drop I get the negative that I lack the privilege prvCreateCustomControl

Is there another way to import without relying on this privilege?

**Comment by scottdurow** [comment]
Hi @Fernando-Rivero - It sounds like you are importing the solution into the default environment or an environment without dataverse. You will need to create a developer environment to build your app (https://learn.microsoft.com/en-us/power-platform/developer/create-developer-environment) and then deploy to an environment with Dataverse.

**Comment by scottdurow** [comment]
Closed due to inactivity
