### ISSUE TITLE
Error importing solution - The solution file is invalid.

### ISSUE THREAD

**Issue by ChrisShack** [scottdurow/power-drag-drop#42]
Hi Scott, 
Firstly thank you for your efforts and your videos, for me and my colleagues they are really helpful. 
We need to create a scheduling board for our operations sites, the power drag drop solution is really useful, but we are having problems importing the solution to any of our Power apps environments, the error message is below:

The solution file is invalid. The compressed file must contain the following files at its root: solution.xml, customizations.xml, and [Content_Types].xml. Customization files exported from previous versions of Microsoft Dynamics 365 are not supported.

We have tried on a number of environments, personal developer environments and shared development environments, we have premium subscriptions linked to out D365F&O licences. 

We are downloading the zip from GitHub and importing without any manipulation. Could you advise please?
Thank you, Chris Shackleton

**Comment by scottdurow** [comment]
Hi @ChrisShack.
Some things to check:
1. You are importing PowerDropDrop_managed_1_1_0.zip from https://github.com/scottdurow/power-drag-drop/releases/tag/v1.1.0
2.  You are following all of the steps at https://learn.microsoft.com/en-us/power-apps/maker/data-platform/import-update-export-solutions

**Comment by ChrisShack** [comment]
Hi Scott, 
Thank you for getting back, we were importing the zip from the link on the YouTube video - https://github.com/scottdurow/power-drag-drop, rather than the /releases/tag/v1.1.0 zip. This imported fine. 

Thanks for your help,
Chris
