### ISSUE TITLE
Count of items in zone

### ISSUE THREAD

**Issue by donsvensen** [scottdurow/power-drag-drop#6]
Hi Scott

First of all awesome component 💪

Is it possible to have a property like AllItems so the number of items in a zone can be counted ?

Best regards
Erik

**Comment by scottdurow** [comment]
Hi @donsvensen - thanks for trying out PowerDragDrop! 🚀

Perhaps the `CurrentItems` property on the master drop zone would work for this? You can then filter by the `DropZoneId` on each row to get the count of items in each drop zone.

Would that work?

**Comment by donsvensen** [comment]
Hi @scottdurow 

Works like a charm - thx for clarifying

CountRows(
    Filter(
        pcf_ProductsToCheck.CurrentItems,
        DropZoneId = "NoAnswer" //dropzoneID for masterzone
    )
)
