### ISSUE TITLE
Unable to add new fields to any Drag and Drop components 

### ISSUE THREAD

**Issue by craigmday** [scottdurow/power-drag-drop#72]
I have been using the Drag and Drop components to create a task scheduler and it is working very well. Recently (within the last few weeks), I lost the ability to add new fields to any drag and drop components. I am able to view and select fields, but when I click OK to add them, they do not get added. 

I have the same issue for every drag and drop control in my app. I created a new app from scratch and added a drag and drop component and had the same issue. 

Has anyone else experience this? If so, is there any known fix? I suspect it may be related to a Power Platform update.

**Comment by RolfReichmuth** [comment]
Hallo ich habe das gleiche Problem, kann auch keine Felder hinzufügen. Ich benutze eine Collection

**Comment by yaseralhosani** [comment]
+1

I agree. I believe this issue is related to the Canvas version. It seems that I can no longer change to a version earlier than 3.24054.19.

**Comment by craigmday** [comment]
Thank you for confirming, Rolf and Yaser. Glad it's not just me! Hopefully, it will be addressed soon.

**Comment by BaptisteWetterwald** [comment]
+1

**Comment by rijamg** [comment]
Having the same issue here

**Comment by deivinni** [comment]
+1 Também estou tendo problemas relacionados a isso.

**Comment by valeriaelias** [comment]
+1

**Comment by shrd-BravoDelta** [comment]
+1!! I am having the same issue too. I thought i did something wrong, but i am not.

**Comment by NickPorterRSM** [comment]
+1, having the same issue; cannot add Fields to any components

**Comment by zenobre** [comment]
Same issue here, i cannot add new fields to the component

**Comment by Devu97** [comment]
Same issue, we are also unable to add new fields..is this going to be addressed?

**Comment by jagdpixel** [comment]
+1 - thought i was going insane. has to be related to the new canvas update

**Comment by jagdpixel** [comment]
> +1 - thought i was going insane. has to be related to the new canvas update

Also - created a brand new app with all preview functionality turned off (i.e. no 'New Analysis Engine') and still get the same behavior. Unable to add fields to a Power Drag and Drop control

**Comment by MetonIvictus** [comment]
This has to do with the new version of powerapps the way colletions work has changed. We are having the same issues. The retired feature that i expect causes this issue "Collection access in component scope". You can enable it in the settings but it does not solve the issue.

**Comment by scottdurow** [comment]
Hello - this is due to a regression with the most recent version of Power Apps which - a fix is being worked on - in the meantime you can use the fix described here - https://github.com/microsoft/powercat-code-components/issues/349

**Comment by jagdpixel** [comment]
> Hello - this is due to a regression with the most recent version of Power Apps which - a fix is being worked on - in the meantime you can use the fix described here - [microsoft/powercat-code-components#349](https://github.com/microsoft/powercat-code-components/issues/349)

Many thanks, fix works as described, and will allow you to add fields
