### ISSUE TITLE
Component not compatible with new power apps engine

### ISSUE THREAD

**Issue by carelele** [scottdurow/power-drag-drop#73]
I've been using the component for some months without any problem. I activated the new analysis  engine for power apps, which is in preview right now, and now i can't use it. It looks transparent and it does not contain any data. I tryed to deactivate the engine  and it worked again. It looks like it is not compatible somehow

**Comment by MetonIvictus** [comment]
We have experienced the same issue. Microsoft has released a new version of PowerApps where collections no longer works like it did. 

Microsoft has retiered the feature "Collection Access in Component Scope". (you can still enable it in the retired section but this will not fix the PCF component)

@scottdurow, could you please look into this? As of now we cannot use this component anymore.

**Comment by scottdurow** [comment]
Hi @MetonIvictus - You are right there is a change in the most recent version of Power Apps - but it is a regression which will be fixed in a future version. In the meantime you can use the work around described in https://github.com/microsoft/powercat-code-components/issues/349

**Comment by scottdurow** [comment]
cc @carelele

**Comment by scottdurow** [comment]
This appears to be fixed in Authoring version 3.24071.12 of Power Apps Studio 🥳
